CREATE TABLE Products (
id SERIAL,
name VARCHAR(60) NOT NULL UNIQUE,
description VARCHAR(240),
brand VARCHAR(60) NOT NULL,
type VARCHAR(60) NOT NULL,
price DECIMAL(5, 2) NOT NULL,
quantity INT NOT NULL,
image VARCHAR(120),
CONSTRAINT primary_key PRIMARY KEY (id)
);

CREATE TABLE Users (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
name VARCHAR(60) NOT NULL,
username VARCHAR(20) NOT NULL,
password LONG VARCHAR NOT NULL,
admin BOOLEAN DEFAULT FALSE,
PRIMARY KEY (id)
);